"""followers

Revision ID: 112721ca4a39
Revises: c37ef4d227d9
Create Date: 2019-02-25 23:07:42.253246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112721ca4a39'
down_revision = 'c37ef4d227d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
